### ISSUE TITLE
You do not have sufficient permissions to access this page.

### ISSUE THREAD

**Issue by MyLittlePolygon** [reduxframework/redux-converter#2]
Hi @dovy thanks for you awesome work, but I have a little issue, when I try convert SMOF to Redux i get this message "You do not have sufficient permissions to access this page." when I clicked in "Proceed here" link on "This is your panel converted. Saving will be saved to a transient value which gets reset every hour. Proceed here to get the export code you would need to migrate from SMOF to Redux."

I try make the conversion on localhost, I dont know if this happen because this, can you help me?

Thanks man

**Comment by dovy** [comment]
Hey there. Can you tell me a bit about your setup? Do you have SMOF/OptionTree running? Can you access the rest of the panel?

**Comment by bookmarkingbug** [comment]
Hi dovy I get this error message too, 
i setup my theme in a network of sites. I'm running SMOF, I can access the rest of the panel

and also I have this 
"Notice: Undefined index: title in C:\xampp\htdocs\multi\wp-content\plugins\redux-converter\admin\class.converter.SMOF.php on line 204"
http://prntscr.com/2qiqda

additionally after setting up the "convert to redux" tab and saving the option I got this
http://prntscr.com/2qit0u

my settings
http://prntscr.com/2qitg4

thank you for this awesome framework
cheers

**Comment by dovy** [comment]
You are using the plugin. That's so odd. I am not sure why that would occur... Can you try running the redux-framework plugin from the code in the github repo instead of what's on wordpress.org?

https://github.com/ReduxFramework/ReduxFramework

Let me know if that fixes it.

**Comment by bookmarkingbug** [comment]
just tried that earlier same result..

**Comment by dovy** [comment]
So odd. SMOF in a theme. You have both the converter redux-framework installed as plugins?

**Comment by bookmarkingbug** [comment]
yes I installed both the converter and the redux-framework as plugin.. 
I'm running trough the codes right now... I'll get back to you when I found something

**Comment by dovy** [comment]
Ok, use the code for ReduxFramework from this repo: https://github.com/ReduxFramework/ReduxFramework

I'll be pushing an update to Wordpress.org tomorrow. That's the issue. Works fine as long as you do that.  ;)

**Comment by VladNov** [comment]
Hi Dovy,

Same here, using SMOF and both plugins, the framework and converter, were downloaded from WP today.

**Comment by dovy** [comment]
Can you send me your plugin/theme so I can duplicate it? Dovy@reduxframework.com. Http://wetransfer.com works great. ;)

**Comment by VladNov** [comment]
Just sent. Thank you for looking into this.

**Comment by dovy** [comment]
Ok, so I just downloaded and used this. The issue is this. Inside redux-converter are a few files that need to be read. Basically if read and write permissions are not correct it won't work.

Also if you're not using Redux 3.1.8 it won't work.

@VladNov I just downloaded your theme, activated it, installed Redux Converter, then I installed Redux Framework. I went to the convert to redux tab and clicked on both convert and download. Both worked without a flaw.

I installed all of these via the theme/plugin interface.

Can you try uninstalling what you have, and installing using the standard interfaces? I think that will resolve the concern.

**Comment by VladNov** [comment]
Hi Dovy,

I installed both plugins using the WP Plugins interface, but still no joy. I'll try it once more on different WP installation. Thank you for your help.

**Comment by dovy** [comment]
New push was just made. SHOULD resolve this issue.

**Comment by iyork** [comment]
i'm getting the same error. new wp install 3.8.1, converter 1.1.1 and framework 3.8.1.21. 
wp admin panel | (top or side SMOF 2 Redux) converter | Convert to Redux! 
"Proceed here to get the export code"
result: You do not have sufficient permissions to access this page.
at page <URL>/wp-admin/admin.php?page=SMOF_2_redux

everything cloned from GIT tonight after removing panel installed from zips and from WP.org and reinstalling it, twice. same error.

any idea where to check? permissions issue somewhere? plugin files all chmod - 755, framework file 755 or 644

**Comment by dovy** [comment]
Did you install redux framework?

**Comment by iyork** [comment]
yes, <quote: framework 3.8.1.21> by git clone.

i installed the previous version 3.8.1.20 through the WordPress Admin panel, and got the permissions error, then deleted the framework, and reinstalled through git clone (bash shell) same error, deleted it, tried again through the master zip download, but same error. Then i saw the update 3.8.1.21 and tried it also through the admin panel and git clone installs. no luck.

**Comment by AdrianBotea** [comment]
I am having the same problem "You do not have sufficient permissions to access this page." on localhost.
Is there any solution as it will be really helpful not to rewrite the hole OptionTree code

**Comment by dovy** [comment]
For sure. Send me your theme anyone/everyone. dovy@reduxframework.com   http://wetransfer.com. I'll see why this isn't working.  ;)

**Comment by AdrianBotea** [comment]
So can I use the ReduxFramework.config.php file if I keep getting the permission error ? If yes then how ?
Thanks

**Comment by jgclifton** [comment]
Also having this issue - bit of a roadblock for me.

**Comment by dovy** [comment]
That would help a ton. Please do.

dovy@reduxframework.com
Skype: dovydigital

**Comment by iyork** [comment]
ok let me Skype you before i drive home and you can log in and have a look around. (it’s production, so be aware!)

**Comment by dovy** [comment]
@iyork It's working as expected...

**Comment by dovy** [comment]
OK EVERYONE. I see the error. I had a bad link in the header. Download the newest version from WP.org or this repo and all will work. Sorry about that.
