### ISSUE TITLE
Unknown index

### ISSUE THREAD

**Issue by eriktailor** [reduxframework/redux-converter#3]
Hello,

I just converted my theme's Option-Tree based options panel to Redux with your plugin and it seems it's working correctly although i recieve the following error message:
<b>Notice: Undefined index: value in C:\xampp\htdocs\appster\wp-content\plugins\redux-converter\admin\class.converter.OptionTree.php on line 141</b>

Any ideas what can cause this?

Many thanks,
Erik

**Comment by dovy** [comment]
I am so sorry for not seeing this earlier. Can you pop me your theme/plugin for me to debug this? dovy@reduxframework.com   http://wetransfer.com is a great way to send it.

If you can do this I'll fix that error.  ;)

**Comment by dovy** [comment]
Let me know if this is not resolved.
