### ISSUE TITLE
Issue with config file generator

### ISSUE THREAD

**Issue by someonegp** [reduxframework/redux-converter#4]
Hello!
I tested Redux Converter with the SMOF Example Theme and some others with WP 3.9 and 3.8.3. When I tried to generate the config file there is an error:
Fatal error:  Call to a member function get_contents() on a non-object in F:\PATH\wp-content\plugins\redux-converter-master\admin\class.converter.base.php on line 91

Any ideas?

**Comment by someonegp** [comment]
I made workaround by replace wp_filesystem->get-contents with file_get_contents. But I have a question how to convert from this https://github.com/devinsays/options-framework-theme to SMOF/REDUX ?

**Comment by highergroundstudio** [comment]
I had the same problem and this fixed it. @someonepl want to fork and fix this or do you want me to?

**Comment by dovy** [comment]
Issue has been fixed and pushed.

I'll get to work on the options framework conversion along with my Vafpress converter.  ;)

**Comment by highergroundstudio** [comment]
Hey @dovy I upgraded to the newest version but this problem still persists just so you know. I will fork and pull request to show you.

**Comment by dovy** [comment]
Good call. I'll push here in a min.

**Comment by dovy** [comment]
Pushed. Please verify.

**Comment by highergroundstudio** [comment]
Verified with previously converted theme. Works great.What changed to make Developer Mode Enabled?

**Comment by dovy** [comment]
It's ALWAYS been enabled. You just have to manually set dev_mode to false before you ship.  ;)

Keep it in dev_mode unless you want to ship. Be in dev_mode before you report bugs so you can let us know exact error lines numbers and such.  ;)

Best of luck.

**Comment by dovy** [comment]
Basically we added that notice because users were shipping with dev_mode and their users would get all those upgrade notices. Not a good thing.  :P

**Comment by highergroundstudio** [comment]
Got it, cool! Thanks!

**Comment by dovy** [comment]
Best of luck.

If you like Redux, please do some or all of the following:
- Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
- Like us: http://facebook.com/ReduxFramework
- Follow us: http://twitter.com/ReduxFramework
- Donate to keep this project going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
