### ISSUE TITLE
How to use Redux Converter?

### ISSUE THREAD

**Issue by ghost** [reduxframework/redux-converter#5]
Hello!

How to use Redux Converter?
Please write tutorial!
SMOF framework to Redux

Thank you!

**Comment by kakoma** [comment]
Thanks for bringing this up KardiWeb. The plugin is actually self-explanatory when it works-which is most of the time. When it doesn't however, you have to jump through so many hoops trying to figure out what's wrong.
<strong>Instructions for use (from what I had to do to get it working.)</strong>

<ol>
<li>Install Redux Framework  plugin</li>
<li>Install Redux Converter plugin</li>
<li>Activate the plugin. On activation, you'll see a menu item (Under "settings") called "SMOF 2 Redux" (If your theme's using SMOF")</li>
<li>Use that menu item to do your migration</li>
</ol>

Note that it failed to work with my 3.9.0 and 3.9.1 WP versions; no menu item appeared in both cases (which left me groping in the dark). It finally worked when I used WP 3.5 (Don't judge; it's a test install)

**Comment by dovy** [comment]
Sorry you all! I need to get back on this. Been busy with this: http://wpdemo.io  ;)

Hopefully some time this week.

**Comment by ghost** [comment]
Thank you!

Activate demo sample data and import ReduxFramework.config.php content?
Replace global variable $smof_data to $redux_demo or own variable?
Delete theme admin directory? etc..

**Comment by dovy** [comment]
By default the converter uses the $smof_data variable so you don't have to change a thing.

You can delete the theme admin dir once you've converted.

All your data will be migrated.

Sorry for the delay. My wife just had twins. It's been a couple of CRAZY months.

**Comment by ghost** [comment]
I warmly congratulate the twins!

Thank you very much the help!

**Comment by dovy** [comment]
No problem. Best of luck.

If you like Redux, please do some or all of the following:
- Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
- Like us: http://facebook.com/ReduxFramework
- Follow us: http://twitter.com/ReduxFramework
- Donate to keep this project going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW

**Comment by kakoma** [comment]
Congratulations Dovy! In Uganda, you'd get a special name for fathering
twins-you'd be called Salongo i.e. Salongo Dovy
Off to check off those items; hadn't done any {Oh the shame I live with :-(
}

On Fri, Aug 15, 2014 at 8:16 AM, Dovy Paukstys notifications@github.com
wrote:

> No problem. Best of luck.
> 
> If you like Redux, please do some or all of the following:
> - Review us:
>   http://wordpress.org/support/view/plugin-reviews/redux-framework
> - Like us: http://facebook.com/ReduxFramework
> - Follow us: http://twitter.com/ReduxFramework
> - Donate to keep this project going:
>   https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ReduxFramework/redux-converter/issues/5#issuecomment-52275176
> .

## 

http://kakoma.ug
http:somanystories.ug http://somanystories.ug

**Comment by nazmul007** [comment]
I see lots of error when this plugin activate is it still work?
