### ISSUE TITLE
Call to undefined method ReduxFramework::get_fold()

### ISSUE THREAD

**Issue by wpexplorer** [reduxframework/redux-converter#6]
When downloading the plugins (Redux + Redux Converter) from WP.org I get this error on activation:

<pre>
Fatal error: Call to undefined method ReduxFramework::get_fold() in /Applications/MAMP/htdocs/wp-content/plugins/redux-converter/admin/class.converter.base.php on line 200
</pre>

**Comment by dovy** [comment]
Issue has been fixed and pushed.
